### PR TITLE
Configuration

### PR DESCRIPTION
**Pull request by Wackerbarth**
This is a part of the effort to separate aspects of the printer from characteristics of the object that stores the configuration.

The aspects of the printer are "values" stored in a "database".
They are separate from the characteristics of the storage of the database.

### CODE REVIEW

**Comment by ThatWileyGuy** [comment]
Firstly, this breaks the M19 unittest.

More generally, though, I'm not sure what the end goal of these changes is. So far, it looks like you're moving Replicape/Reach versions from something that's detected and configured at runtime to something that's specified in the user configuration. I don't really see how that's an improvement - the available hardware is something we can probe at runtime and discover perfectly every time, so moving that information into the config just seems like a needless opportunity for a user to mess things up?

**Comment by Wackerbarth** [comment]
In addition to making the configuration just a data store and handling the controller/hardware functions in separate modules, the idea is to examine the hardware and post the result in the information database. Then the configuration can be built from those values. Among other aspects, this will make it easier for us to test portions of the system without requiring the actual hardware.

**Comment by Wackerbarth** [comment]
For the current release cycle, this is all of the change that I am trying to get into the code. The cretion of the "Hardware.py" module is intended to extract the part that is truly hardware specific from the general operation. We could create an additional data store, but I see little gain in doing so. One purpose in separating the identification of the hardware from the construction of the objects that will perform the functional implementation is that we are able to detail the specifics of each board revision in a data file rather than in more difficult to edit and runtime footprint increasing python code. These data files can be processed by the already present data store mechanism. It is my intention to remove the system provided "configuration files" from the user area and access them directly from the programs file space. To the extent permitted, the user will still be able to provide override settings in their "local" file.

**Comment by ThatWileyGuy** [comment]
This is a sweeping refactor that we never reached consensus on and are now unlikely to.

**Pull request closed without merging**
