### PR TITLE
DEPRECATE this branch

### PR DESCRIPTION
**Pull request by Wackerbarth**

### CODE REVIEW

**Comment by ThatWileyGuy** [comment]
It's probably worth checking with @eliasbakken before making this branch.

**Comment by Wackerbarth** [comment]
I've tried to port his changes to 2.2 but, because I don't understand parts of the code, need a bit of assistance in finishing doing so. In any case, this branch has diverged so significantly from the current development that we need to base things on the newer branches.

**Comment by eliasbakken** [comment]
Sorry for not having followed up on the development of this. Can we keep the revolve branch a little bit longer, and when I start up work again, I can do it on my own repository and do pull requests like everyone else? I do like to keep things tidy, just don't have time to deal with ATM.

**Comment by Wackerbarth** [comment]
As with other older branches, I expect that we will keep the actual branch around for a while as a resource. However, by changing the README, it will be clear that (1) this code is obsolete and we will not be supporting it and (2) any development based on these commits is likely to require significant rework in order to be moved to our current development.  I'm doing a significant rework of the configuration system and much of the parts of this code that are different from its contemporary `develop`branch  will easily drop into the new structure. I continue to carry them forward in my own repository, including a group of differences that I haven't been able to understand. Cleaning those up to become the base for new PR changes is probably the best point for integration at this time.

**Pull request merged**
