### PR TITLE
Correct homing description

### PR DESCRIPTION
**Pull request by ThatWileyGuy**

### CODE REVIEW

**Comment by Wackerbarth** [comment]
The description seems to be correct. However, I find it to still be confusing. Unfortunately, the measurements are made in the reference frame of the endstop.  I think that it would be easier to explain if the numbers were all in the bed reference. But that implies that we must negate the result. (But not the parking position which is in the bed coordinates)

**Comment by ThatWileyGuy** [comment]
I agree - one of the ongoing efforts we have is to support "upgrading" a configuration in-place when a new version of Redeem starts up. One of the major reasons to do that was that our current endstop configuration is fairly confusing and it probably makes sense to design a more comprehensible one, but we needed a way to convert people from the old one to the new one rather than breaking all their configs.

**Comment by Wackerbarth** [comment]
As for upgrading, we should add a "configuration version" to the system section of every file. And, if it is missing, default to the version as of redeem 2.0.  Then, if the version is not "current", we can abort out (assuming that we get the configuration stuff that Daryl and I have been messing with -- it reverts to restarting with just the "default.cfg", and nothing else) and refer the user to an upgrade plugin.

**Comment by ThatWileyGuy** [comment]
Yes, that's in-progress in https://github.com/intelligent-agent/redeem/pull/29 . Unfortunately, Andrew got busy and that PR has stalled somewhat.

**Pull request merged**
