### PR TITLE
User configurable thermal management

### PR DESCRIPTION
**Pull request by darylbond**
Allows for the control of fans (and heaters at some point in the near future) in an arbitrary and user defined manner. Implemented as a network of pre-defined functional units that are configured and connected by the user according to definitions provided in a config file. Credit should go to Richard Wackerbarth for the initial suggestion of this approach @Wackerbarth on slack). This has required the transition to a config parser that allows nested sections as well as the ability to add sections not found in default.cfg when parsing printer.cfg or local.cfg. 

The user is allowed to insert whatever they like into [Temperature Control]. Each sub-section will define a unit which may be connected to other units as well as fans (and heaters). The name of the sub-section gives the name of the unit and is used for identification purposes. Each unit must also define a type as well as other type specific quantities. Implemented units are shown in the example given below where available types are:

- alias
- minimum
- maximum
- difference
- constant-control
- proportional-control
- on-off-control

Available temperature sensors are:
- thermistor-*
- ds18b20-*

```
[Temperature Control]

[[AmbientTemperature]]
type = minimum
input-0 = ds18b20-0
input-1 = ds18b20-1

[[HeadTemperature]]
type = maximum
input-0 = thermistor-E
input-1 = thermistor-H

[[CoolantTemperature]]
type = alias
input = ds18b20-2

[[CoolantWarmup]]
type = difference
input-1 = CoolantTemperature
input-0 = AmbientTemperature

[[CaseFan]]
type = constant-control
input = 255

[[CoolantFan]]
type = proportional-control
input = CoolantWarmup
target_temperature = 0
proportional = 0.1
max_speed = 255
min_speed = 64
ok_range = 5.0

[[CoolantPump]]
type = on-off-control
input = HeadTemperature
on_temperature = 80
off_temperature = 60
on_power = 100
off_power = 0
```

these units may then be attached to Fans according to 

```
[Fans]
[[Fan-0]]
add-to-M106 = True

[[Fan-1]]
input = CoolantPump

[[Fan-2]]
input = CoolantFan

[[Fan-3]]
input = CaseFan
```

or equivalently

```
[[Fan-3]]
input=255
```

Note that you could also attach directly to a fan from a control unit by defining `ouput = Fan-0`. I just haven't tested that part of the implementation just yet.

These changes alse necessitate changes to the OctoPrint plugin for Redeem. These can be seen at [octoprint_redeem](https://github.com/intelligent-agent/octoprint_redeem/compare/master...darylbond:nested_config). This modification means that if I import a config that has something not in default.cfg then as long as it can be parsed by ConfigObj then it will become printer.cfg. When redeem is restarted any non-compliant entries will be flagged by Redeem during the cascading config processing. This approach prevents crashing Redeem while also giving it all repsonsibility for discrimination.

One thing that I will draw to your attention is that I am setting Fan channels via the internal config instance. This allows for fan initialisation to be carried out purely from the config dict. However, I expect that this will be picked up as a change and written to local.cfg if/when a save is performed. This shouldn't matter, as it will just be overwritten, but it will unnecessarily populate local.cfg. 

I'm sure there is more that I have missed so please ask questions and let me know what you think. This pull request is intended primarily as an opportunity to shape this implementation into something that works well for everyone, as I expect it is something that will have a large impact on the usability of the Replicape ecosystem.
Daryl

### CODE REVIEW

**Comment by goeland86** [comment]
@ThatWileyGuy @eliasbakken @ajmirsky Can you guys take a look and debate what you think? There's a stack of comments recently in the development channel on slack to read up on if you like.

**Comment by darylbond** [comment]
@Wackerbarth thanks for the comments, greatly appreciated. 

Having a gcode control unit makes sense. Having other control units, such as full PID, is definitely on the cards. Probably when heaters are implemented.

I'm not sure that we need an UNUSED unit as this is functionally equivalent to constant-control with value of zero, as currently implemented. If the user doesn't supply a [[Fan-*]] in the higher level configs then it will be unused by default. 

My current thinking is to allow the user to ignore the whole control unit approach and just set a default fan speed and connection to M106/M107 directly. I am sure the control network approach will confuse some people and I would like a simple fallback option.

**Comment by eliasbakken** [comment]
It seems very flexible, so that is great! 
But flexibility comes at a cost, so we need do a few things: 
1) To document this well, perhaps in the config files or with a link to the documentation in the octoprint_redeem plugin. 
2) Also, it's important to have a good default/fallback like Wackerbarth says. Something that will allow a user to get something going right away, perhaps all fans on M106 or something. 
3) Lastly is some form of feedback if there is an error in the config file. The current (in master) implementation is pretty crude just checking against default, but if that is not to be used any more, we need to replace it and at the very least give a warning in syslog (I think I saw that in the code). Even better is to give an alarm that gets pushed into OctoPrint. The alarm is not yet operational since the user has not connected OctoPrint to Redeem at the time the config is read, but the plan is to queue all alarms happening during startup and send them only when a connection is established.

**Comment by Wackerbarth** [comment]
I definitely agree with Elias that DOCUMENTATION is essential.

As to error reporting, I also support the apparent direction of assuring that no configuration entries prevent Redeem from starting (even if it is then in a “do nothing” state) and assure that any configuration errors are reported to the operational host connection.

**Comment by darylbond** [comment]
I have updated the documentation in default.cfg but will post it again here for visibility.

I would like to include an example for a number of different scenarios, but I think the wiki would be the better place for that. 

```
[Temperature Control]
# Thermal management is implemented in Redeem through a user configurable network 
# of sensors, heaters and fans. The user specifies the nodes of this network in this 
# section of the configuration file. Each node is a uniquely configured instance 
# from a pre-defined set, all of which are shown below. This approach allows
# for a high degree of flexibility in setting up when fans turn on/off, the
# type of control logic that is used for each heater/fan, and even allowing 
# multiple sensors to control their behaviour. 
#
# allowed types are : alias, difference, maximum, minimum, constant-control, 
#   on-off-control, pid-control, proportional-control, safety, gcode
#
# templates for control units are given below.
#
#[[AliasUnitName]]
#type = alias
#input = <names of temperature>
#
#[[ComparisonUnitName]]
#type = difference, maximum, or minimum
#input_0 = <name of input>
#input_1 = <name of input>
#
#[[ConstantName]]
#type = constant-control
#value = <number in range 0..255>
#output = <name of output>
#
#[[SafetyName]]
#type = safety
#max_rise_rate = <number, deg/sec>
#max_fall_rate = <number, deg/sec>
#min_temp = <number, deg>
#max_temp = <number, deg>
#min_rise_rate = <number, deg/sec>
#min_rise_offset = <number, deg>
#min_rise_delay = <number, sec>
#input = <input sensor name>
#heater = <heater name>
#
#[[OnOffName]]
#type=on-off-control
#target_value = <number>
#on_offset = <number, turn on when value <= target + on_offset>
#off_offset = <number, turn off when value <= target + off_offset>
#on_value = <number in range 0..255>
#off_value = <number in range 0..255>
#sleep = <number, sec, time between control updates>
#output = <output name>
#
#
#[[ProportionalControlName]]
#type = proportional-control
#input = <name of input>
#target_value = <number, desired temperature>
#proportional = <number, multiplier of error>
#max_value = <number in range 0..255>
#min_value = <number in range 0..255>
#ok_range = <number, output=min_value if input is within ok_range of target>
#sleep = <number, sec, time between control updates>
#output = <name of output>
#
#[[PIDControlName]]
#type = pid-control
#input = <name of input>
#target_value =  <number, desired temperature>
#pid_Kp =  <number, proportional constant>
#pid_Ti = <number, integral constant>
#pid_Td = <number, derivative constant>
#ok_range = <number, output=0 if input is within ok_range of target>
#max_value = <number in range 0..255>
#sleep = <number, sec, time between control updates>
#
#[[CommandName]]
#type = gcode
#command = <G- or M-code/s, multiple codes allowed as a comma separated list>
#output = <output name/s, multiple outputs allowed as a comma separated list>
#
# NOTES:
#   <> when connecting a control unit to a heater or fan the connection may be defined from either unit (input or output).
#   <> 'difference' units return (input_0 - input_1)
#   <> 'gcode' units currently only accept M106 or M107
#   <> in 'safety' units the min_rise_* parameters are used to check for attached/detached/misconnected sensor/heater pairs
#       when power is supplied to the heater, we expect min_rise_rate temperature rise per second, as long as temp is min_rise_offset 
#       below the heaters target temperature and we are min_rise_delay seconds after starting heating.
#   <> multiple safety units may be attached to each heater but each safety can only define one input and one output
#   <> safety inputs must be temperature sensors, or an alias thereof
```

**Comment by Wackerbarth** [comment]
@darylbond - Please review your description of "OnOff". The descriptions for the offsets do not make sense.
One of them should be "Temp greater than some_value" and the other "Temp less than another_value".

**Pull request merged**
