### PR TITLE
Prevent timing out controller when unknown G/Mcodes are received.

### PR DESCRIPTION
**Pull request by zaped212**
Add stubs for M73, and M126 Mcodes.
This prevents print delays when unknown gcodes are sent to the printer.
This looks to be caused by the printer not responding with any message back to the sender ( octoprint ).

This only stubs out the M73, and M126 commands.

### CODE REVIEW

**Comment by zaped212** [comment]
There may be a more appropriate change to respond to the sender on unknown gcodes but I wasnt sure where / how to pull that off.

**Comment by Wackerbarth** [comment]
Rather than chasing individual M-codes, I would like to see a solution that allows the user to define a macro for any arbitrary code(s) of their choosing, then a particular user could decide what they want as a response on a case-by-case basis be it "ignore", "generate a message", or anything else.

That would allow each user to extend the list of accepted codes without impacting other users who never see a particular code or restricting the type of response that the user wants generated.

**Comment by ThatWileyGuy** [comment]
@Wackerbarth That solves a different and not really related problem. I don't have a problem with adding more flexible macro support, but right now the problem is just that most users never realize the funny timeouts are because Redeem doesn't support a specific M-code.

@zaped212 I don't have any issue signing off on this if you want to go ahead with it. I think a more general solution would be to return a warning that would show up in the OctoPrint console and then return an OK so OctoPrint continues on. That would mean the default behavior for an unknown code changes from a timeout to a textual warning.

**Comment by zaped212** [comment]
@ThatWileyGuy, I was thinking along the same lines as you as that would affect all unknown gcodes.
I was just looking at the code and wasnt quite getting where I would need to put the logic.

It is looking like:
def enqueue(self, gcode) where it checks if the command is None

though im not sure how to get the response setup to send back to Octoprint.
Should I just issue something like:
self.printer.send_message(g.prot, "ok \n")

**Comment by ThatWileyGuy** [comment]
That would work, but it looks like you can just do `self.printer.reply(gcode)`.

I'm pretty sure OctoPrint is just looking for a leading "ok," so you could probably get the warning in via something like `gcode.set_reply("ok Unknown GCode: " + gcode.code())`.

**Comment by zaped212** [comment]
Had a chance to test this, and was using the wrong function call.

Here is the output seen in the log: WARNING  tried to enqueue an unknown gcode: M126
Here is what octoprint sees:
Send: M126
Recv: ok Unknown GCode: M126

Verified that no timeout occurs.

**Comment by Wackerbarth** [comment]
We need to document that Redeem will no longer treat ANY unknown Gcode as a ERROR, but it will treat it as a NO-OP and issue a warning.

**Pull request merged**
