### PR TITLE
Apply Probe Z offset to G30

### PR DESCRIPTION
**Pull request by zaped212**
G30 previously took the X and Y probe offsets into account when
probing a given position. This allow getting bed information for
where the hotend should be instead of measuring at an offset
position.

This takes the Z offset into account when returning the probe
information. This also removes the offset from being indirectly
applied with the G33 commands.

### CODE REVIEW

**Comment by zaped212** [comment]
I went through the failed builds and know that I need to do some formatting changes, but I looked over the G30 and G33 tests that were failing and I believe the test code is incorrect.

The proposed changes apply a probe z_offset before the value is returned and the current test does not specify any z_offset and could be why the returned value is off by 11 meters.
The G30 test should be modified to perform two tests:

1. One test that applies a probe z_offset of 0, and that should cause the current test to succeed again, as the changes I made would be ignored.
2. A second section of the test that applies a non-zero probe offset. This would verify that the changes to the g30 command are valid.

For the g33 test the issue is very similar.
Previously the z_offset was getting applied inside the G33 command, but for the test the execution step ( printer.processor.execute ), which would call the g30 command and apply the offset, has been mocked preventing the G30 command from actually running and adding the expected z_offset causing the probed values to be 1.2mm off from the expected values.

I will push up a new change that addresses the formatting issues, but want to talk about the testing and figure out how to adjust the test code before proceeding.

**Comment by zaped212** [comment]
You are correct, I wrote that message, submitted it, and then got to thinking about the wording.

If you could point me towards the test code I will try to get a change pushed up for that.

Note: Even if the tests are updated they will continue to fail until this change is merged.

**Comment by zaped212** [comment]
Sorry, hit close instead of comment.

**Comment by Wackerbarth** [comment]
I think that @ThatWileyGuy was implying that this modifies the "expected behavior" and, as a result, the modification to the "behavior" tests need to be included in the same PR along with the code changes.

I am in agreement with you that the present behavior can be improved. To me, a useful probing exercise should present only the residual "error" and any adjustments would be additive rather than absolute. If someone wants absolute values, they can clear all of the adjustment components to "zero" before probing. I also suggest that applying the results of `G33` or `G29` should adjust ALL components, including Z height, to minimize the resulting error. I find it problematic to perform "bed leveling" and have that operation invalidate the Z height with no way to continue probing with the tilt corretions applied.

**Comment by zaped212** [comment]
Thanks @Wackerbarth 
I have no idea why I missed that. I think I was looking inside of the redeem directory.
I will get the tests updated and formatting fixed.

**Comment by zaped212** [comment]
I am working on modifying the G30 test currently but believe I am running into another issue.

I modified the test to apply a z_offset of 0.00 but looks like either its not applying properly or I am missing something.
`    def test_gcodes_G30_S_with_P(self):
      offset_z = self.printer.config.set('Probe', 'offset_z',
                                         str(0.000))    # Set probe offset to 0

      offset_z = self.printer.config.getfloat('Probe', 'offset_z') * 1000
>     self.assertEqual(offset_z, 0.0)
E     AssertionError: 11220.0 != 0.0`

**Comment by zaped212** [comment]
@Wackerbarth @ThatWileyGuy 
What else do you guys need for this to be merged?

**Comment by zaped212** [comment]
I have verified this using my deltabot

**Comment by goeland86** [comment]
While testing this probe offset change for G33 results, I encountered an odd behavior:
My x/y/z offsets were more or less right (within 0.4mm of the bed all over, just slightly slanted for some reason). Ran G33. My Z=0 was now a good 4cm above the bed...

Restarted redeem, re-ran G33 and now the bed leveling seemed accurate.
I'm still confused by what's happened. @zaped212 did you run into something similar or is it just an odd runtime bug when I changed the Z probe offset using G34 and didn't restart redeem in between?

**Comment by Wackerbarth** [comment]
I'm running into similar issues on my cartesian test box w/o this PR. Not sure that this is directly related to his change. I think that we need to have a discussion about the expected behavior of all the operators associated with probing and leveling.

**Comment by goeland86** [comment]
@Wackerbarth then it's more likely an issue with G34 that's saving the value to disk correctly but that somehow isn't correctly updated in the running instance, isn't it?

**Comment by zaped212** [comment]
@Wackerbarth , @goeland86 
I have not noticed any of the issues you have mentioned in the above comments.
Each time that I run the G33 command with this change I have been able to glide the nozzle consistently right over the surface.

Besides organizing the probe offsets to only the G30 command, I would not expect there to be any functional differences between the two code sets.

**Comment by goeland86** [comment]
Validated as functioning for me as well. The bad offset probes were not reproducible.

**Comment by Wackerbarth** [comment]
You are probably on a Delta. There, the probe stops all actuators at the same time. The problem is that that is not the case for Cartesian kinematics.

**Pull request merged**
