### PR TITLE
More NewPathPlanner fixups

### PR DESCRIPTION
**Pull request by ThatWileyGuy**

### CODE REVIEW

**Comment by ThatWileyGuy** [comment]
With these changes, I can successfully print a Benchy on both my printers. Currently testing probing.

**Comment by ThatWileyGuy** [comment]
Probing works for me, with the proviso that the bed leveling matrix has to be cleared before probing.

**Comment by Wackerbarth** [comment]
Is the probing just the "tilt" vs "slant" aspect?

**Comment by Wackerbarth** [comment]
After this is combined with NewPathPlanner, there are a few cleanups that will be made to prepare the combination for merging into 2.2.x.

**Pull request merged**
